//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lombard_Soldatov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platez
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platez()
        {
            this.Prodaza = new HashSet<Prodaza>();
        }
    
        public string ID_Tovar { get; set; }
        public Nullable<decimal> Summa { get; set; }
        public string Kraynyaya_data_plateza { get; set; }
        public string Facticheskaya_data_plateza { get; set; }
        public string Sotrudnik { get; set; }
        public string Status_plateza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prodaza> Prodaza { get; set; }
    }
}
