//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lombard_Soldatov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovary()
        {
            this.Prodaza = new HashSet<Prodaza>();
        }
    
        public string ID_Tovara { get; set; }
        public string Nazvanie { get; set; }
        public string Tip { get; set; }
        public Nullable<System.DateTime> Data_sdachi { get; set; }
        public string Ocenochnaya_Stoimost { get; set; }
        public string Sotrydnik { get; set; }
        public Nullable<decimal> Symma_pod_zalog { get; set; }
        public Nullable<decimal> Symma_vykupa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prodaza> Prodaza { get; set; }
    }
}
