//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lombard_Soldatov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long ID_User { get; set; }
        public string ID_Sotrudnik { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Prodaza Prodaza { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
